[project]
name = 'Collective-Film-Production-DAO'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Collective-Film-Production-DAO]
path = 'contracts/Collective-Film-Production-DAO.clar'
clarity_version = 3
epoch = 3.1

[contracts.reputation-system]
path = 'contracts/reputation-system.clar'
clarity_version = 3
epoch = 3.1

[contracts.project-milestones]
path = 'contracts/project-milestones.clar'
clarity_version = 3
epoch = 3.1

[contracts.proposal-escrow]
path = 'contracts/proposal-escrow.clar'
clarity_version = 3
epoch = 3.1

[contracts.proposal-time-extension]
path = 'contracts/proposal-time-extension.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
